BenchmarkProblems:
  # dgemm NT
  - ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: False

  # dgemm NN
  - ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True

  # dgemm TN
  - ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: False
      UseBeta: True

  # dgemm TT
  - ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: True
      UseBeta: True

