GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 8
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  DataInitType: 0
  KernelTime: True
  MaxMacroTileRatio: 2

BenchmarkProblems:
  - # zgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: z
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes: [ [1536], [1536], [2], [1536] ]
        - EdgeType: ["Shift"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - LocalWriteCoalesceGroupA: [ True ]
        - LocalWriteCoalesceGroupB: [ False ]
      ForkParameters:
        - GroupShape: [ 0, 2 ]
        - ThreadTileShape: [ 0, 2 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - NumThreads: [128, 256]
        - ThreadTileNumElements: [4, 8, 16 ]
        - IntraSplitU: [ 1, 2, 4, 8, 16 ]
        - DepthU: [ 4, 8, 16, 32 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes: [ [32, 32, 32, 2000], [32, 32, 32, 2000], [2], [1536] ]

  - # zgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: z
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes: [ [1536], [1536], [2], [1536] ]
        - EdgeType: ["Shift"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - LocalWriteCoalesceGroupA: [ True ]
        - LocalWriteCoalesceGroupB: [ True ]
      ForkParameters:
        - GroupShape: [ 0, 2 ]
        - ThreadTileShape: [ 0, 2 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - NumThreads: [128, 256]
        - ThreadTileNumElements: [4, 8, 16 ]
        - IntraSplitU: [ 1, 2, 4, 8, 16 ]
        - DepthU: [ 4, 8, 16, 32]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes: [ [32, 32, 32, 2000], [32, 32, 32, 2000], [2], [1536] ]

  - # zgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: z
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes: [ [1536], [1536], [2], [1536] ]
        - EdgeType: ["Shift"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - LocalWriteCoalesceGroupA: [ False ]
        - LocalWriteCoalesceGroupB: [ False ]
      ForkParameters:
        - GroupShape: [ 0, 2 ]
        - ThreadTileShape: [ 0, 2 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - NumThreads: [128, 256]
        - ThreadTileNumElements: [4, 8, 16 ]
        - IntraSplitU: [ 1, 2, 4, 8, 16 ]
        - DepthU: [ 4, 8, 16, 32]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes: [ [32, 32, 32, 2000], [32, 32, 32, 2000], [2], [1536] ]

  - # zgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: z
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
        - WorkGroupMapping: [-1]
      BenchmarkCommonParameters:
        - ProblemSizes: [ [1536], [1536], [2], [1536] ]
        - EdgeType: ["Shift"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - LocalWriteCoalesceGroupA: [ False ]
        - LocalWriteCoalesceGroupB: [ True ]
      ForkParameters:
        - GroupShape: [ 0, 2 ]
        - ThreadTileShape: [ 0, 2 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - NumThreads: [128, 256]
        - ThreadTileNumElements: [4, 16, 32 ]
        - IntraSplitU: [ 1, 2, 4, 8, 16 ]
        - DepthU: [ 4, 8, 16, 32]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes: [ [32, 32, 32, 2000], [32, 32, 32, 2000], [2], [1536] ]

LibraryLogic:
  ScheduleName: Fiji
  DeviceNames: ["Fiji Nano"]
  BranchPenalty: 0

LibraryClient:
