Parameters:
  Name: rocBLAS
  PrintLevel: 1
  ForceRedoBenchmarkProblems: False
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 16
  ValidationPrintValids: False
  ShortNames: True
  MergeFiles: True
  PlatformIdx: 0
  DeviceIdx: 0
  DataInitType: 0

BenchmarkProblems:
  # cgemm NN
  - ProblemType:
      OperationType: GEMM
      DataType: c
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupSchedule: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
    ForkParameters:
      - WorkGroupShape: [ 0 ]
      - ThreadTileShape: [ 0 ]
      - WorkGroupEdge: [8, 16]
      - ThreadTileEdge: [2, 4, 6, 8]
      - NumLoadsCoalescedA: [ 1, 2, 3, 4, 6 ]
      - NumLoadsCoalescedB: [ 1, 2, 3, 4, 6 ]
    BenchmarkForkParameters:
      - LoopUnroll: [8, 16]
    JoinParameters:
      - MacroTile
      - DepthU
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # cgemm NT
  - ProblemType:
      OperationType: GEMM
      DataType: c
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupSchedule: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
    ForkParameters:
      - WorkGroupEdge: [8, 16]
      - WorkGroupShape: [ 0 ]
      - ThreadTileEdge: [2, 4, 6, 8]
      - ThreadTileShape: [ 0 ]
    BenchmarkForkParameters:
      - NumLoadsCoalescedA: [ 1, 2, 3, 4, 6 ]
      - NumLoadsCoalescedB: [ 1, 2, 3, 4, 6 ]
      - LoopUnroll: [8, 16]
    JoinParameters:
      - MacroTile
      - DepthU
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # cgemm TN
  - ProblemType:
      OperationType: GEMM
      DataType: c
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupSchedule: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
    ForkParameters:
      - WorkGroupEdge: [8, 16]
      - WorkGroupShape: [ 0 ]
      - ThreadTileEdge: [2, 4, 6, 8]
      - ThreadTileShape: [ 0 ]
    BenchmarkForkParameters:
      - NumLoadsCoalescedA: [ 1, 2, 3, 4, 6 ]
      - NumLoadsCoalescedB: [ 1, 2, 3, 4, 6 ]
      - LoopUnroll: [8, 16]
    JoinParameters:
      - MacroTile
      - DepthU
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # cgemm TT
  - ProblemType:
      OperationType: GEMM
      DataType: c
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupSchedule: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
    ForkParameters:
      - WorkGroupEdge: [8, 16]
      - WorkGroupShape: [ 0 ]
      - ThreadTileEdge: [2, 4, 6, 8]
      - ThreadTileShape: [ 0 ]
    BenchmarkForkParameters:
      - NumLoadsCoalescedA: [ 1, 2, 3, 4, 6 ]
      - NumLoadsCoalescedB: [ 1, 2, 3, 4, 6 ]
      - LoopUnroll: [8, 16]
    JoinParameters:
      - MacroTile
      - DepthU
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

LibraryLogic:
  Dilation: 3
  Threshold: 0.1

LibraryClient:
