GlobalParameters:
  MinimumRequiredVersion: 3.2.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: True

BenchmarkProblems:
  ########################################
  # NN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4080, 4080, 2, 2880 ]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - VectorWidth: [1]
        - WorkGroupMapping: [8]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
        - DepthU: [ 4, 8, 16 ]
        - GlobalSplitU: [2, 4, 8]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
        - GlobalSplitU
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 3000], [32, 32, 32, 3000], [1], [2880] ]

  ########################################
  # NN - Assembly
  ########################################
    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4080, 4080, 2, 2880 ]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 6, 8 ]
          - [ 4, 8 ]
          - [ 6, 6 ]
          - [ 4, 6 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [  8, 16, 1 ]
          - [  8,  8, 1 ]
        - DepthU: [ 4, 8, 16 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 6000], [32, 32, 32, 6000], [1], [2880] ]


  ########################################
  # NT - standard
  ########################################
  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4080, 4080, 2, 2880 ]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - VectorWidth: [1]
        - WorkGroupMapping: [8]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16 ]
        - GlobalSplitU: [2, 4, 8]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 3000], [32, 32, 32, 3000], [1], [2880] ]

  ########################################
  # NT - Assembly
  ########################################
    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4080, 4080, 2, 2880 ]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
        - WorkGroupMapping: [8]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 6, 8 ]
          - [ 4, 8 ]
          - [ 6, 6 ]
          - [ 4, 6 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [  8, 16, 1 ]
          - [  8,  8, 1 ]
        - DepthU: [ 4, 8, 16 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 6000], [32, 32, 32, 6000], [1], [2880] ]


  ########################################
  # TN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4080, 4080, 2, 2880 ]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - VectorWidth: [1]
        - WorkGroupMapping: [8]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  2,  4,16 ]
          - [  4,  4, 8 ]
          - [  4,  8, 4 ]
          - [  4,  4,16 ]
          - [  4,  8, 8 ]
          - [  8,  8, 4 ]
        - DepthU: [8, 16, 32 ]
        - GlobalSplitU: [2, 4, 8]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
        - GlobalSplitU
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 3000], [32, 32, 32, 3000], [1], [2880] ]

  ########################################
  # TN - Assembly
  ########################################
    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4080, 4080, 2, 2880 ]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
        - WorkGroupMapping: [8]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 6, 8 ]
          - [ 4, 8 ]
          - [ 6, 6 ]
          - [ 4, 6 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [  8, 16, 1 ]
          - [  8,  8, 1 ]
        - DepthU: [ 8, 16, 32 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 6000], [32, 32, 32, 6000], [1], [2880] ]

  ########################################
  # TT - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
        - WorkGroupMapping: [-1]
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4080, 4080, 2, 2880 ]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - VectorWidth: [1]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - WorkGroupMapping: [-1, -8]
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
        - DepthU: [ 4, 8, 16 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 3000], [32, 32, 32, 3000], [1], [2880] ]

  ########################################
  # TT - Assembly
  ########################################
    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4080, 4080, 2, 2880 ]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
        - WorkGroupMapping: [8]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
          - [ 2, 4 ]
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [  8, 16, 1 ]
          - [  8,  8, 1 ]
        - DepthU: [ 4, 8, 16 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 6000], [32, 32, 32, 6000], [1], [2880] ]

LibraryLogic:

LibraryClient:
