GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 2
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True

BenchmarkProblems:
  ########################################
  # NN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 2880, 2880, 2, 2880 ]
        - EdgeType: ["ShiftPtr"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
        - LocalWriteCoalesceGroupA: [ True ]
        - LocalWriteCoalesceGroupB: [ False ]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  2,  4,16 ]
          - [  4,  4, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 1 ]
          - [  4,  4,16 ]
          - [  4,  8, 8 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
        - GlobalSplitU: [1, 2, 3, 4, 5, 6, 7, 8]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
        - GlobalSplitU
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [1], [2880] ]
          - Exact: [  35, 8457, 1, 1760 ]
          - Exact: [  35, 8457, 1, 2048 ]
          - Exact: [  35, 8457, 1, 2560 ]
          - Exact: [  35, 8457, 1, 4096 ]
          - Exact: [1760,   16, 1, 1760 ]
          - Exact: [1760,   32, 1, 1760 ]
          - Exact: [1760,   64, 1, 1760 ]
          - Exact: [1760,  128, 1, 1760 ]
          - Exact: [1760, 7000, 1, 1760 ]
          - Exact: [2048,   16, 1, 2048 ]
          - Exact: [2048,   32, 1, 2048 ]
          - Exact: [2048,   64, 1, 2048 ]
          - Exact: [2048,  128, 1, 2048 ]
          - Exact: [2048, 7000, 1, 2048 ]
          - Exact: [2560,   16, 1, 2560 ]
          - Exact: [2560,   32, 1, 2560 ]
          - Exact: [2560,   64, 1, 2560 ]
          - Exact: [2560,  128, 1, 2560 ]
          - Exact: [2560, 7000, 1, 2560 ]
          - Exact: [3072,   16, 1, 1024 ]
          - Exact: [3072,   32, 1, 1024 ]
          - Exact: [3072,   64, 1, 1024 ]
          - Exact: [3072,  128, 1, 1024 ]
          - Exact: [4096,   16, 1, 4096 ]
          - Exact: [4096,   32, 1, 4096 ]
          - Exact: [4096,   64, 1, 4096 ]
          - Exact: [4096,  128, 1, 4096 ]
          - Exact: [4096, 7000, 1, 4096 ]
          - Exact: [5124, 9124, 1, 1760 ]
          - Exact: [5124, 9124, 1, 2048 ]
          - Exact: [5124, 9124, 1, 2560 ]
          - Exact: [5124, 9124, 1, 4096 ]
          - Exact: [7680,   16, 1, 2560 ]
          - Exact: [7680,   32, 1, 2560 ]
          - Exact: [7680,   64, 1, 2560 ]
          - Exact: [7680,  128, 1, 2560 ]

  ########################################
  # NN - 4kB
  ########################################
    - # BenchmarkProblemSizeGroup - 4kB
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4096, 4096, 1, 4096 ]
        - EdgeType: ["ShiftPtr"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
        - LocalWriteCoalesceGroupA: [ True ]
        - LocalWriteCoalesceGroupB: [ False ]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  2,  4,16 ]
          - [  4,  4, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 1 ]
          - [  4,  4,16 ]
          - [  4,  8, 8 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
        - MaxOccupancy: [ 1, 10 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [  35, 8457, 1, 1760 ]
          - Exact: [  35, 8457, 1, 2048 ]
          - Exact: [  35, 8457, 1, 2560 ]
          - Exact: [  35, 8457, 1, 4096 ]
          - Exact: [1760,   16, 1, 1760 ]
          - Exact: [1760,   32, 1, 1760 ]
          - Exact: [1760,   64, 1, 1760 ]
          - Exact: [1760,  128, 1, 1760 ]
          - Exact: [1760, 7000, 1, 1760 ]
          - Exact: [2048,   16, 1, 2048 ]
          - Exact: [2048,   32, 1, 2048 ]
          - Exact: [2048,   64, 1, 2048 ]
          - Exact: [2048,  128, 1, 2048 ]
          - Exact: [2048, 7000, 1, 2048 ]
          - Exact: [2560,   16, 1, 2560 ]
          - Exact: [2560,   32, 1, 2560 ]
          - Exact: [2560,   64, 1, 2560 ]
          - Exact: [2560,  128, 1, 2560 ]
          - Exact: [2560, 7000, 1, 2560 ]
          - Exact: [3072,   16, 1, 1024 ]
          - Exact: [3072,   32, 1, 1024 ]
          - Exact: [3072,   64, 1, 1024 ]
          - Exact: [3072,  128, 1, 1024 ]
          - Exact: [4096,   16, 1, 4096 ]
          - Exact: [4096,   32, 1, 4096 ]
          - Exact: [4096,   64, 1, 4096 ]
          - Exact: [4096,  128, 1, 4096 ]
          - Exact: [4096, 7000, 1, 4096 ]
          - Exact: [5124, 9124, 1, 1760 ]
          - Exact: [5124, 9124, 1, 2048 ]
          - Exact: [5124, 9124, 1, 2560 ]
          - Exact: [5124, 9124, 1, 4096 ]
          - Exact: [7680,   16, 1, 2560 ]
          - Exact: [7680,   32, 1, 2560 ]
          - Exact: [7680,   64, 1, 2560 ]
          - Exact: [7680,  128, 1, 2560 ]


  ########################################
  # NT - standard
  ########################################
  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 2880, 2880, 2, 2880 ]
        - EdgeType: ["ShiftPtr"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
        - LocalWriteCoalesceGroupA: [ True ]
        - LocalWriteCoalesceGroupB: [ True ]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  2,  4,16 ]
          - [  4,  4, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 1 ]
          - [  4,  4,16 ]
          - [  4,  8, 8 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [1], [2880] ]
          - Exact: [1760, 7133, 1, 1760 ]
          - Exact: [2048, 7133, 1, 2048 ]
          - Exact: [2560, 7133, 1, 2560 ]
          - Exact: [3072, 7435, 1, 1024 ]
          - Exact: [4096, 7133, 1, 4096 ]
          - Exact: [7680, 5481, 1, 2560 ]

  ########################################
  # NT - 4kB
  ########################################
    - # BenchmarkProblemSizeGroup - 4kB
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4096, 4096, 1, 4096 ]
        - EdgeType: ["ShiftPtr"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
        - LocalWriteCoalesceGroupA: [ True ]
        - LocalWriteCoalesceGroupB: [ True ]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  2,  4,16 ]
          - [  4,  4, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 1 ]
          - [  4,  4,16 ]
          - [  4,  8, 8 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
        - MaxOccupancy: [ 1, 10 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1760, 7133, 1, 1760 ]
          - Exact: [2048, 7133, 1, 2048 ]
          - Exact: [2560, 7133, 1, 2560 ]
          - Exact: [3072, 7435, 1, 1024 ]
          - Exact: [4096, 7133, 1, 4096 ]
          - Exact: [7680, 5481, 1, 2560 ]


  ########################################
  # TN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 2880, 2880, 2, 2880 ]
        - EdgeType: ["ShiftPtr"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
        - LocalWriteCoalesceGroupA: [ False ]
        - LocalWriteCoalesceGroupB: [ False ]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  2,  4,16 ]
          - [  4,  4, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 1 ]
          - [  4,  4,16 ]
          - [  4,  8, 8 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
        - GlobalSplitU: [1, 2, 3, 4, 5, 6, 7, 8]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
        - GlobalSplitU
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [1], [2880] ]
          - Exact: [  35, 8457, 1, 1760 ]
          - Exact: [  35, 8457, 1, 2048 ]
          - Exact: [  35, 8457, 1, 2560 ]
          - Exact: [  35, 8457, 1, 4096 ]
          - Exact: [1760,   16, 1, 1760 ]
          - Exact: [1760,   32, 1, 1760 ]
          - Exact: [1760,   64, 1, 1760 ]
          - Exact: [1760,  128, 1, 1760 ]
          - Exact: [1760, 7000, 1, 1760 ]
          - Exact: [2048,   16, 1, 2048 ]
          - Exact: [2048,   32, 1, 2048 ]
          - Exact: [2048,   64, 1, 2048 ]
          - Exact: [2048,  128, 1, 2048 ]
          - Exact: [2048, 7000, 1, 2048 ]
          - Exact: [2560,   16, 1, 2560 ]
          - Exact: [2560,   32, 1, 2560 ]
          - Exact: [2560,   64, 1, 2560 ]
          - Exact: [2560,  128, 1, 2560 ]
          - Exact: [2560, 7000, 1, 2560 ]
          - Exact: [3072,   16, 1, 1024 ]
          - Exact: [3072,   32, 1, 1024 ]
          - Exact: [3072,   64, 1, 1024 ]
          - Exact: [3072,  128, 1, 1024 ]
          - Exact: [4096,   16, 1, 4096 ]
          - Exact: [4096,   32, 1, 4096 ]
          - Exact: [4096,   64, 1, 4096 ]
          - Exact: [4096,  128, 1, 4096 ]
          - Exact: [4096, 7000, 1, 4096 ]
          - Exact: [5124, 9124, 1, 1760 ]
          - Exact: [5124, 9124, 1, 2048 ]
          - Exact: [5124, 9124, 1, 2560 ]
          - Exact: [5124, 9124, 1, 4096 ]
          - Exact: [7680,   16, 1, 2560 ]
          - Exact: [7680,   32, 1, 2560 ]
          - Exact: [7680,   64, 1, 2560 ]
          - Exact: [7680,  128, 1, 2560 ]

  ########################################
  # TN - 4kB
  ########################################
    - # BenchmarkProblemSizeGroup - 4kB
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 4096, 4096, 1, 4096 ]
        - EdgeType: ["ShiftPtr"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
        - LocalWriteCoalesceGroupA: [ False ]
        - LocalWriteCoalesceGroupB: [ False ]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  2,  4,16 ]
          - [  4,  4, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 1 ]
          - [  4,  4,16 ]
          - [  4,  8, 8 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
        - MaxOccupancy: [ 1, 10 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [  35, 8457, 1, 1760 ]
          - Exact: [  35, 8457, 1, 2048 ]
          - Exact: [  35, 8457, 1, 2560 ]
          - Exact: [  35, 8457, 1, 4096 ]
          - Exact: [1760,   16, 1, 1760 ]
          - Exact: [1760,   32, 1, 1760 ]
          - Exact: [1760,   64, 1, 1760 ]
          - Exact: [1760,  128, 1, 1760 ]
          - Exact: [1760, 7000, 1, 1760 ]
          - Exact: [2048,   16, 1, 2048 ]
          - Exact: [2048,   32, 1, 2048 ]
          - Exact: [2048,   64, 1, 2048 ]
          - Exact: [2048,  128, 1, 2048 ]
          - Exact: [2048, 7000, 1, 2048 ]
          - Exact: [2560,   16, 1, 2560 ]
          - Exact: [2560,   32, 1, 2560 ]
          - Exact: [2560,   64, 1, 2560 ]
          - Exact: [2560,  128, 1, 2560 ]
          - Exact: [2560, 7000, 1, 2560 ]
          - Exact: [3072,   16, 1, 1024 ]
          - Exact: [3072,   32, 1, 1024 ]
          - Exact: [3072,   64, 1, 1024 ]
          - Exact: [3072,  128, 1, 1024 ]
          - Exact: [4096,   16, 1, 4096 ]
          - Exact: [4096,   32, 1, 4096 ]
          - Exact: [4096,   64, 1, 4096 ]
          - Exact: [4096,  128, 1, 4096 ]
          - Exact: [4096, 7000, 1, 4096 ]
          - Exact: [5124, 9124, 1, 1760 ]
          - Exact: [5124, 9124, 1, 2048 ]
          - Exact: [5124, 9124, 1, 2560 ]
          - Exact: [5124, 9124, 1, 4096 ]
          - Exact: [7680,   16, 1, 2560 ]
          - Exact: [7680,   32, 1, 2560 ]
          - Exact: [7680,   64, 1, 2560 ]
          - Exact: [7680,  128, 1, 2560 ]

  ########################################
  # TT - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
        - WorkGroupMapping: [-1]
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Exact: [ 2880, 2880, 2, 2880 ]
        - EdgeType: ["ShiftPtr"]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
        - LocalWriteCoalesceGroupA: [ False ]
        - LocalWriteCoalesceGroupB: [ True ]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  2,  4,16 ]
          - [  4,  4, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 1 ]
          - [  4,  4,16 ]
          - [  4,  8, 8 ]
          - [  8,  8, 4 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
        - PrefetchGlobalRead: [False, True]
        - PrefetchLocalRead: [False, True]
        - DepthU: [ 4, 8, 16, 32 ]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
        - WorkGroupMapping: [-64, -32, -16, -8, -4, -2, -1, 1, 2, 4, 8, 16, 32, 64]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [1], [2880] ]

LibraryLogic:
  ScheduleName: Fiji
  DeviceNames: ["R9 Nano"]

LibraryClient:
