GlobalParameters:
  Name: Fiji
  PrintLevel: 1
  ForceRedoBenchmarkProblems: False
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 8
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 16
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  DataInitType: 0

BenchmarkProblems:
  # dgemm NN
  - ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupMapping: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
    ForkParameters:
      - WorkGroupShape: [ 0 ]
      - ThreadTileShape: [ 0 ]
      - WorkGroupEdge: [8, 16]
      - ThreadTileEdge: [2, 4, 6, 8]
      - NumLoadsCoalescedA: [ 1, -1 ]
      - NumLoadsCoalescedB: [ 1, -1 ]
      - LoopUnroll: [8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # dgemm NT
  - ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupMapping: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
    ForkParameters:
      - WorkGroupEdge: [8, 16]
      - WorkGroupShape: [ 0 ]
      - ThreadTileEdge: [2, 4, 6, 8]
      - ThreadTileShape: [ 0 ]
      - NumLoadsCoalescedA: [ 1, -1 ]
      - NumLoadsCoalescedB: [ 1, -1 ]
      - LoopUnroll: [8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # dgemm TN
  - ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupMapping: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
    ForkParameters:
      - WorkGroupEdge: [8, 16]
      - WorkGroupShape: [ 0 ]
      - ThreadTileEdge: [2, 4, 6, 8]
      - ThreadTileShape: [ 0, 1 ]
      - NumLoadsCoalescedA: [ 1, -1 ]
      - NumLoadsCoalescedB: [ 1, -1 ]
      - LoopUnroll: [8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # dgemm TT
  - ProblemType:
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupMapping: [ -1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
    ForkParameters:
      - WorkGroupEdge: [8, 16]
      - WorkGroupShape: [ 0 ]
      - ThreadTileEdge: [2, 4, 6, 8]
      - ThreadTileShape: [ 0 ]
      - NumLoadsCoalescedA: [ 1, -1 ]
      - NumLoadsCoalescedB: [ 1, -1 ]
      - LoopUnroll: [8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

LibraryLogic:
  BranchPenalty: 0

LibraryClient:
