GlobalParameters:
  Name: Fiji
  PrintLevel: 1
  ForceRedoBenchmarkProblems: False
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 8
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 16
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  DataInitType: 0

BenchmarkProblems:
  # cgemm NN
  - ProblemType:
      OperationType: GEMM
      DataType: c
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - EdgeType: ["Branch"]
      - WorkGroupMapping: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
      - NumLoadsCoalescedA: [-1]
      - NumLoadsCoalescedB: [1]
      - GroupShape: [ 0 ]
      - ThreadTileShape: [ 0 ]
    ForkParameters:
      - NumThreads: [64, 128, 256]
      - ThreadTileNumElements: [4, 16, 36, 64]
      - SplitU: [ 1, 2, 4, 8, 16 ]
      - DepthU: [ 8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # cgemm NT
  - ProblemType:
      OperationType: GEMM
      DataType: c
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - EdgeType: ["Branch"]
      - WorkGroupMapping: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
      - ThreadTileShape: [ 0 ]
      - NumLoadsCoalescedA: [-1]
      - NumLoadsCoalescedB: [-1]
      - GroupShape: [ 0 ]
    ForkParameters:
      - NumThreads: [64, 128, 256]
      - ThreadTileNumElements: [4, 16, 36, 64]
      - SplitU: [ 1, 2, 4, 8, 16 ]
      - DepthU: [ 8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # cgemm TN
  - ProblemType:
      OperationType: GEMM
      DataType: c
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - EdgeType: ["Branch"]
      - WorkGroupMapping: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
      - NumLoadsCoalescedA: [1]
      - NumLoadsCoalescedB: [1]
      - GroupShape: [ 0 ]
      - ThreadTileShape: [ 0 ]
    ForkParameters:
      - NumThreads: [64, 128, 256]
      - ThreadTileNumElements: [4, 16, 36, 64]
      - SplitU: [ 1, 2, 4, 8, 16 ]
      - DepthU: [ 8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

  # cgemm TT
  - ProblemType:
      OperationType: GEMM
      DataType: c
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [2880], [2880], [2], [1536] ]
      - EdgeType: ["Branch"]
      - WorkGroupMapping: [ -1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
      - ThreadTileShape: [ 0 ]
      - NumLoadsCoalescedA: [1]
      - NumLoadsCoalescedB: [-1]
      - GroupShape: [ 0 ]
    ForkParameters:
      - NumThreads: [64, 128, 256]
      - ThreadTileNumElements: [4, 16, 36, 64]
      - SplitU: [ 1, 2, 4, 8, 16 ]
      - DepthU: [ 8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [32, 32, 32, 4000], [32, 32, 32, 4000], [2], [1536] ]

LibraryLogic:
  BranchPenalty: 0

LibraryClient:
