GlobalParameters:
  MinimumRequiredVersion: 4.3.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 2
  LibraryPrintDebug: False
  NumElementsToValidate: 256
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 0
  DataInitTypeBeta : 0
# PrintSolutionRejectionReason: True
# SolutionSelectionAlg: 1
# PrintWinnersOnly: 1
# ExitOnFails: 0

BenchmarkProblems:

  ########################################
  # NN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 8 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [1], [64] ]

    - # BenchmarkProblemSizeGroup - M,N < VW
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 4 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1], [1], [1], [64] ]
          - Range: [ [1], [64], [1], [64] ]
          - Range: [ [64], [1], [1], [64] ]

    - # BenchmarkProblemSizeGroup - M*384 384*N (small)
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
          - [ 6, 4 ]
          - [ 4, 6 ]
        - WorkGroup:
          - [ 16,  8,  1 ]
          - [  8, 16,  1 ]
          - [ 16, 16,  1 ]
        - DepthU: [ 2, 4, 8, 12 ]
        - AssertSummationElementMultiple: [2]
        - AssertFree0ElementMultiple: [2]
        - AssertFree1ElementMultiple: [2]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [   384,   384, 1, 384 ]
          - Exact: [   768,   768, 1, 384 ]
          - Exact: [  1152,  1152, 1, 384 ]
          - Exact: [  1536,  1536, 1, 384 ]
          - Exact: [  1920,  1920, 1, 384 ]
          - Exact: [  2304,  2304, 1, 384 ]
          - Exact: [  2688,  2688, 1, 384 ]
          - Exact: [  3072,  3072, 1, 384 ]
          - Exact: [  3456,  3456, 1, 384 ]
          - Exact: [  3840,  3840, 1, 384 ]
          - Exact: [  4224,  4224, 1, 384 ]
          - Exact: [  4608,  4608, 1, 384 ]
          - Exact: [  4992,  4992, 1, 384 ]
          - Exact: [  5376,  5376, 1, 384 ]
          - Exact: [  5760,  5760, 1, 384 ]
          - Exact: [  6144,  6144, 1, 384 ]
          - Exact: [  6528,  6528, 1, 384 ]
          - Exact: [  6912,  6912, 1, 384 ]
          - Exact: [  7296,  7296, 1, 384 ]
          - Exact: [  7680,  7680, 1, 384 ]
          - Exact: [  8064,  8064, 1, 384 ]
          - Exact: [  8448,  8448, 1, 384 ]
          - Exact: [  8832,  8832, 1, 384 ]
          - Exact: [  9216,  9216, 1, 384 ]
          - Exact: [  9600,  9600, 1, 384 ]
          - Exact: [  9984,  9984, 1, 384 ]
          - Exact: [ 10368, 10368, 1, 384 ]
          - Exact: [ 10752, 10752, 1, 384 ]
          - Exact: [ 11136, 11136, 1, 384 ]
          - Exact: [ 11520, 11520, 1, 384 ]
          - Exact: [ 11904, 11904, 1, 384 ]
          - Exact: [ 12288, 12288, 1, 384 ]
          - Exact: [ 12672, 12672, 1, 384 ]
          - Exact: [ 13056, 13056, 1, 384 ]
          - Exact: [ 13440, 13440, 1, 384 ]
          - Exact: [ 13824, 13824, 1, 384 ]
          - Exact: [ 14208, 14208, 1, 384 ]
          - Exact: [ 14592, 14592, 1, 384 ]
          - Exact: [ 14976, 14976, 1, 384 ]
          - Exact: [ 15360, 15360, 1, 384 ]
          - Exact: [ 15744, 15744, 1, 384 ]
          - Exact: [ 16128, 16128, 1, 384 ]
          - Exact: [ 16512, 16512, 1, 384 ]
          - Exact: [ 16896, 16896, 1, 384 ]
          - Exact: [ 17280, 17280, 1, 384 ]
          - Exact: [ 17664, 17664, 1, 384 ]
          - Exact: [ 18048, 18048, 1, 384 ]
          - Exact: [ 18432, 18432, 1, 384 ]
          - Exact: [ 18816, 18816, 1, 384 ]
          - Exact: [ 19200, 19200, 1, 384 ]
          - Exact: [ 19584, 19584, 1, 384 ]
          - Exact: [ 19968, 19968, 1, 384 ]
          - Exact: [ 20352, 20352, 1, 384 ]
          - Exact: [ 20736, 20736, 1, 384 ]
          - Exact: [ 21120, 21120, 1, 384 ]
          - Exact: [ 21504, 21504, 1, 384 ]
          - Exact: [ 21888, 21888, 1, 384 ]
          - Exact: [ 22272, 22272, 1, 384 ]
          - Exact: [ 22656, 22656, 1, 384 ]
          - Exact: [ 23040, 23040, 1, 384 ]
          - Exact: [ 23424, 23424, 1, 384 ]
          - Exact: [ 23808, 23808, 1, 384 ]
          - Exact: [ 24192, 24192, 1, 384 ]
          - Exact: [ 24576, 24576, 1, 384 ]
          - Exact: [ 24960, 24960, 1, 384 ]
          - Exact: [ 25344, 25344, 1, 384 ]
          - Exact: [ 25728, 25728, 1, 384 ]
          - Exact: [ 26112, 26112, 1, 384 ]
          - Exact: [ 26496, 26496, 1, 384 ]
          - Exact: [ 26880, 26880, 1, 384 ]
          - Exact: [ 27264, 27264, 1, 384 ]
          - Exact: [ 27648, 27648, 1, 384 ]
          - Exact: [ 28032, 28032, 1, 384 ]
          - Exact: [ 28416, 28416, 1, 384 ]
          - Exact: [ 28800, 28800, 1, 384 ]
          - Exact: [ 29184, 29184, 1, 384 ]
          - Exact: [ 29568, 29568, 1, 384 ]
          - Exact: [ 29952, 29952, 1, 384 ]
          - Exact: [ 30336, 30336, 1, 384 ]
          - Exact: [ 30720, 30720, 1, 384 ]
          - Exact: [ 31104, 31104, 1, 384 ]
          - Exact: [ 31488, 31488, 1, 384 ]
          - Exact: [ 31872, 31872, 1, 384 ]
          - Exact: [ 32256, 32256, 1, 384 ]
          - Exact: [ 32640, 32640, 1, 384 ]
          - Exact: [ 33024, 33024, 1, 384 ]
          - Exact: [ 33408, 33408, 1, 384 ]
          - Exact: [ 33792, 33792, 1, 384 ]
          - Exact: [ 34176, 34176, 1, 384 ]
          - Exact: [ 34560, 34560, 1, 384 ]
          - Exact: [ 34944, 34944, 1, 384 ]
          - Exact: [ 35328, 35328, 1, 384 ]
          - Exact: [ 35712, 35712, 1, 384 ]
          - Exact: [ 36096, 36096, 1, 384 ]
          - Exact: [ 36480, 36480, 1, 384 ]
          - Exact: [ 36864, 36864, 1, 384 ]
          - Exact: [ 37248, 37248, 1, 384 ]
          - Exact: [ 37632, 37632, 1, 384 ]
          - Exact: [ 38016, 38016, 1, 384 ]
          - Exact: [ 38400, 38400, 1, 384 ]
          - Exact: [ 38784, 38784, 1, 384 ]
          - Exact: [ 39168, 39168, 1, 384 ]
          - Exact: [ 39552, 39552, 1, 384 ]
          - Exact: [ 39936, 39936, 1, 384 ]
          - Exact: [ 40320, 40320, 1, 384 ]
          - Exact: [ 40704, 40704, 1, 384 ]
          - Exact: [ 41088, 41088, 1, 384 ]
          - Exact: [ 41472, 41472, 1, 384 ]
          - Exact: [ 41856, 41856, 1, 384 ]
          - Exact: [ 42240, 42240, 1, 384 ]
          - Exact: [ 42624, 42624, 1, 384 ]
          - Exact: [ 43008, 43008, 1, 384 ]
          - Exact: [ 43392, 43392, 1, 384 ]
          - Exact: [ 43776, 43776, 1, 384 ]
          - Exact: [ 44160, 44160, 1, 384 ]
          - Exact: [ 44544, 44544, 1, 384 ]
          - Exact: [ 44928, 44928, 1, 384 ]

LibraryLogic:
    ScheduleName: "vega20"
    DeviceNames: ["Device 66a0", "Device 66a1", "Device 66a7"]
    ArchitectureName: "gfx906"

#   ScheduleName: "vega10"
#   DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860", "Device 6861", "Vega 10 XTX [Radeon Vega Frontier Edition]", "Vega [Radeon RX Vega]"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

#   ScheduleName: "hip"
#   DeviceNames: ["Device 0000"]
#   ArchitectureName: "fallback"

LibraryClient:
