GlobalParameters:
  PrintLevel: 1
  ForceRedoBenchmarkProblems: False
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 16
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  DataInitType: 0

BenchmarkProblems:
  # sgemm NN
  - ProblemType:
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: False

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [512], [512], [512] ]
      - SplitU: [ 1 ]
      - EdgeType: ["Branch"]
        EdgeMultiKernel: [False]
      - WorkGroupMapping: [ 1 ]
      - LoopDoWhile: [False]
      - LoopTail: [True]
      - GroupShape: [ 0 ]
      - ThreadTileShape: [ 0 ]
    ForkParameters:
      - NumThreads: [64, 256]
      - ThreadTileNumElements: [4, 16, 64]
      - LoopUnroll: [8, 16]
    BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [16, 128], [16, 128], [256] ]

LibraryLogic:
  BranchPenalty: 0

LibraryClient:
