GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 2
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True

BenchmarkProblems:
  - # sgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: False

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes: [ [512], [512], [512] ]
        - LocalSplitU: [ 1 ]
        - EdgeType: ["Branch"]
        - WorkGroupMapping: [ 1 ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - GroupShape: [ 0 ]
        - ThreadTileShape: [ 0 ]
      ForkParameters:
        - NumThreads: [64, 256]
        - ThreadTileNumElements: [4, 16, 64]
        - DepthU: [8, 16]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes: [ [16, 128], [16, 128], [256] ]

LibraryLogic:
  ScheduleName: Fiji
  DeviceNames: ["Fiji Nano"]
  BranchPenalty: 0

LibraryClient:
