# benchmark MANY kernel for the 5760 size
GlobalParameters:
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 16
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0

BenchmarkProblems:
  # sgemm NN
  - ProblemType:
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: False

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [5760], 0, 0 ]
      - EdgeType: ["None"]
      - LoopDoWhile: [True]
      - LoopTail: [False]
      - NumLoadsCoalescedA: [-1]
      - NumLoadsCoalescedB: [1]
      - WorkGroupMapping: [1]
      - SplitU: [1]
    ForkParameters:
      - GroupShape: [-2, 0, 2]
      - ThreadTileShape: [-2, 0, 2]
      - NumThreads: [128, 256]
      - ThreadTileNumElements: [16, 32, 36, 64]
      - LoopUnroll: [8, 16]
    #BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    #BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [5760], 0, 0 ]

  # sgemm NT
  - ProblemType:
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: False

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [5760], 0, 0 ]
      - EdgeType: ["None"]
      - LoopDoWhile: [True]
      - LoopTail: [False]
      - NumLoadsCoalescedA: [-1]
      - NumLoadsCoalescedB: [-1]
      - WorkGroupMapping: [1]
      - SplitU: [1]
    ForkParameters:
      - GroupShape: [-2, 0, 2]
      - ThreadTileShape: [-2, 0, 2]
      - NumThreads: [128, 256]
      - ThreadTileNumElements: [16, 32, 36, 64]
      - LoopUnroll: [8, 16]
    #BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    #BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [5760], 0, 0 ]

  # sgemm TN
  - ProblemType:
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: False

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [5760], 0, 0 ]
      - EdgeType: ["None"]
      - LoopDoWhile: [True]
      - LoopTail: [False]
      - NumLoadsCoalescedA: [1]
      - NumLoadsCoalescedB: [1]
      - WorkGroupMapping: [1]
      - SplitU: [1]
    ForkParameters:
      - GroupShape: [-2, 0, 2]
      - ThreadTileShape: [-2, 0, 2]
      - NumThreads: [128, 256]
      - ThreadTileNumElements: [16, 32, 36, 64]
      - LoopUnroll: [8, 16]
    #BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    #BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [5760], 0, 0 ]

  # sgemm TT
  - ProblemType:
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: False

    # keep benchmark as single list to make easier to modify in future
    BenchmarkCommonParameters:
      - ProblemSizes: [ [5760], 0, 0 ]
      - EdgeType: ["None"]
      - LoopDoWhile: [True]
      - LoopTail: [False]
      - NumLoadsCoalescedA: [1]
      - NumLoadsCoalescedB: [-1]
      - WorkGroupMapping: [-1]
      - SplitU: [1]
    ForkParameters:
      - GroupShape: [-2, 0, 2]
      - ThreadTileShape: [-2, 0, 2]
      - NumThreads: [128, 256]
      - ThreadTileNumElements: [16, 32, 36, 64]
      - LoopUnroll: [8, 16]
    #BenchmarkForkParameters:
    JoinParameters:
      - MacroTile
    #BenchmarkJoinParameters:
    BenchmarkFinalParameters:
      - ProblemSizes: [ [5760], 0, 0 ]

