GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  DataInitType: 0

BenchmarkProblems:
  - # sgemm NN
    - # ProblemType
      OperationType: TensorContraction
      DataType: s
      UseBeta: True
      NumIndicesC: 3
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - ProblemSizes: [ [512], [512], [2], [512] ]
        - IntraSplitU: [ 1 ]
        - EdgeType: ["Branch"]
        - WorkGroupMapping: [ 1 ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - GroupShape: [ 0 ]
        - ThreadTileShape: [ 0 ]
      ForkParameters:
        - NumThreads: [64, 256]
        - ThreadTileNumElements: [4, 16, 64]
        - DepthU: [8, 16]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
        - DepthU
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes: [ [16, 128], [16, 128], [2, 2, 4], [256] ]

LibraryLogic:
  ScheduleName: Fiji
  DeviceNames: ["Fiji Nano"]
  BranchPenalty: 0

LibraryClient:
