# test load patterns
GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4

BenchmarkProblems:
  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: False
      TransposeB: True
      UseBeta: False
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - DepthU: [ 16 ]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  8, 16, 1 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]


  - # sgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: False
      TransposeB: False
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - DepthU: [ 16 ]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  8, 16, 1 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

  - # sgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: True
      TransposeB: False
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [-1]
        - DepthU: [ 16 ]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  8, 16, 1 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

  - # sgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: True
      TransposeB: True
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - NumLoadsCoalescedA: [-1]
        - NumLoadsCoalescedB: [1]
        - DepthU: [ 16 ]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [ 8, 8 ]
          - [ 4, 8 ]
          - [ 4, 4 ]
        - WorkGroup:
          - [  8, 16, 1 ]
          - [  8, 16, 2 ]
          - [ 16, 16, 1 ]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

LibraryLogic:
  ScheduleName: Fiji
  DeviceNames: ["R9 Nano"]

LibraryClient:
