# test load patterns
GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4

BenchmarkProblems:
  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: False
      TransposeB: True
      UseBeta: False
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - LocalWriteCoalesceGroupA: [True]
        - LocalWriteCoalesceGroupB: [True]
        - GlobalReadCoalesceVectorA: [True]
        - GlobalReadCoalesceVectorB: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - DepthU: [ 16 ]
        - VectorWidth: [1]
      ForkParameters:
        - GroupShape: [ 0, 2 ]
        - NumThreads: [128, 256 ]
        - ThreadTileShape: [0, 2]
        - ThreadTileNumElements: [16, 32, 36]
        - IntraSplitU: [ 1, 2 ]
      BenchmarkFinalParameters:
        - ProblemSizes: [ [128, 128, 256], [128, 128, 256], [64] ]


  - # sgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: False
      TransposeB: False
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - LocalWriteCoalesceGroupA: [True]
        - LocalWriteCoalesceGroupB: [True]
        - GlobalReadCoalesceVectorA: [True]
        - GlobalReadCoalesceVectorB: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - DepthU: [ 16 ]
        - VectorWidth: [1]
      ForkParameters:
        - GroupShape: [ 0, -2 ]
        - NumThreads: [128, 256 ]
        - ThreadTileShape: [0, -2]
        - ThreadTileNumElements: [16, 32, 36]
        - IntraSplitU: [ 1, 2 ]
      BenchmarkFinalParameters:
        - ProblemSizes: [ [128, 128, 256], [128, 128, 256], [64] ]

  - # sgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: True
      TransposeB: False
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - LocalWriteCoalesceGroupA: [True]
        - LocalWriteCoalesceGroupB: [True]
        - GlobalReadCoalesceVectorA: [True]
        - GlobalReadCoalesceVectorB: [True]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [-1]
        - DepthU: [ 16 ]
        - VectorWidth: [1]
      ForkParameters:
        - GroupShape: [ 0, -2 ]
        - NumThreads: [128, 256 ]
        - ThreadTileShape: [0, 2]
        - ThreadTileNumElements: [16, 32, 36]
        - IntraSplitU: [ 1, 2 ]
      BenchmarkFinalParameters:
        - ProblemSizes: [ [128, 128, 256], [128, 128, 256], [64] ]

  - # sgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: True
      TransposeB: True
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes: [ [8, 32, 0, 75], [8, 32, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["Branch"]
        - LocalWriteCoalesceGroupA: [True]
        - LocalWriteCoalesceGroupB: [True]
        - GlobalReadCoalesceVectorA: [True]
        - GlobalReadCoalesceVectorB: [True]
        - NumLoadsCoalescedA: [-1]
        - NumLoadsCoalescedB: [1]
        - DepthU: [ 16 ]
        - VectorWidth: [1]
      ForkParameters:
        - GroupShape: [ 0, 2 ]
        - NumThreads: [128, 256 ]
        - ThreadTileShape: [0, -2]
        - ThreadTileNumElements: [16, 32, 36]
        - IntraSplitU: [ 1, 2 ]
      BenchmarkFinalParameters:
        - ProblemSizes: [ [128, 128, 256], [128, 128, 256], [64] ]

LibraryLogic:
  ScheduleName: Fiji
  DeviceNames: ["Fiji Nano"]
  BranchPenalty: 100

LibraryClient:
