# test load patterns
GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4

BenchmarkProblems:
  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: False
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [4, 23, 0, 75], [4, 13, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [2, 4]
          - [2, 8]
          - [3, 5]
          - [4, 2]
          - [4, 6]
          - [5, 3]
          - [5, 7]
          - [6, 4]
          - [6, 8]
          - [7, 5]
          - [8, 2]
          - [8, 6]
        - WorkGroup:
          - [  4,  8, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 2 ]
          - [  8, 16, 1 ]
          - [ 16, 16, 1 ]
        - DepthU: [ 16 ]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]


  - # sgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [4, 23, 0, 75], [4, 13, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [2, 5]
          - [3, 2]
          - [3, 6]
          - [4, 3]
          - [4, 7]
          - [5, 4]
          - [5, 8]
          - [6, 5]
          - [7, 2]
          - [7, 6]
          - [8, 3]
          - [8, 7]
          - [8, 8]
        - WorkGroup:
          - [  4,  8, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 2 ]
          - [  8, 16, 1 ]
          - [ 16, 16, 1 ]
        - DepthU: [ 16 ]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

  - # sgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [4, 23, 0, 75], [4, 13, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [2, 2]
          - [2, 6]
          - [3, 3]
          - [3, 7]
          - [4, 4]
          - [4, 8]
          - [5, 5]
          - [6, 2]
          - [6, 6]
          - [7, 3]
          - [7, 7]
          - [8, 4]
        - WorkGroup:
          - [  4,  8, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 2 ]
          - [  8, 16, 1 ]
          - [ 16, 16, 1 ]
        - DepthU: [ 16 ]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

  - # sgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [4, 23, 0, 75], [4, 13, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - NumLoadsCoalescedA: [1]
        - NumLoadsCoalescedB: [1]
        - VectorWidth: [1]
      ForkParameters:
        - ThreadTile:
          - [2, 3]
          - [2, 7]
          - [3, 4]
          - [3, 8]
          - [4, 5]
          - [5, 2]
          - [5, 6]
          - [6, 3]
          - [6, 7]
          - [7, 4]
          - [7, 8]
          - [8, 5]
        - WorkGroup:
          - [  4,  8, 8 ]
          - [  4,  8, 4 ]
          - [  8,  8, 4 ]
          - [  8,  8, 2 ]
          - [  8, 16, 2 ]
          - [  8, 16, 1 ]
          - [ 16, 16, 1 ]
        - DepthU: [ 16 ]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

LibraryLogic:
  ScheduleName: Fiji
  DeviceNames: ["R9 Nano"]

LibraryClient:
