# test load patterns
GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4

BenchmarkProblems:
  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: False
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [4, 23, 0, 75], [4, 13, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - WorkGroup:
          - [  8,  8, 2 ]
        - ThreadTile:
          - [4, 8]
        - DepthU: [ 8 ]
      ForkParameters:
        - GlobalReadCoalesceGroupA: [False, True]
        - GlobalReadCoalesceGroupB: [False, True]
        - GlobalReadCoalesceVectorA: [False, True]
        - GlobalReadCoalesceVectorB: [False, True]
        - NumLoadsCoalescedA: [1, -1]
        - NumLoadsCoalescedB: [1, -1]
        - VectorWidth: [2, 4]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]


  - # sgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [4, 23, 0, 75], [4, 13, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - WorkGroup:
          - [  8,  8, 2 ]
        - ThreadTile:
          - [4, 8]
        - DepthU: [ 8 ]
      ForkParameters:
        - GlobalReadCoalesceGroupA: [False, True]
        - GlobalReadCoalesceGroupB: [False, True]
        - GlobalReadCoalesceVectorA: [False, True]
        - GlobalReadCoalesceVectorB: [False, True]
        - NumLoadsCoalescedA: [1, -1]
        - NumLoadsCoalescedB: [1, -1]
        - VectorWidth: [2, 4]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

  - # sgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [4, 23, 0, 75], [4, 13, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - WorkGroup:
          - [  8,  8, 2 ]
        - ThreadTile:
          - [4, 8]
        - DepthU: [ 8 ]
      ForkParameters:
        - GlobalReadCoalesceGroupA: [False, True]
        - GlobalReadCoalesceGroupB: [False, True]
        - GlobalReadCoalesceVectorA: [False, True]
        - GlobalReadCoalesceVectorB: [False, True]
        - NumLoadsCoalescedA: [1, -1]
        - NumLoadsCoalescedB: [1, -1]
        - VectorWidth: [2, 4]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

  - # sgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
    - # BenchmarkProblemSizeGroup - Standard
      BenchmarkCommonParameters:
        - ProblemSizes:
          - Range: [ [4, 23, 0, 75], [4, 13, 0, 75], [63, 1, 64] ]
        - LoopDoWhile: [False]
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - WorkGroup:
          - [  8,  8, 2 ]
        - ThreadTile:
          - [4, 8]
        - DepthU: [ 8 ]
      ForkParameters:
        - GlobalReadCoalesceGroupA: [False, True]
        - GlobalReadCoalesceGroupB: [False, True]
        - GlobalReadCoalesceVectorA: [False, True]
        - GlobalReadCoalesceVectorB: [False, True]
        - NumLoadsCoalescedA: [1, -1]
        - NumLoadsCoalescedB: [1, -1]
        - VectorWidth: [2, 4]
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [128, 128, 256], [128, 128, 256], [64] ]

LibraryLogic:
  ScheduleName: Fiji
  DeviceNames: ["R9 Nano"]

LibraryClient:
